# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LolaUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Lola(object):
    def setupUi(self, Lola):
        Lola.setObjectName("Lola")
        Lola.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Lola)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-20, -135, 1051, 931))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../G.U.I Material/B.G/Black_Template.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.bg_2 = QtWidgets.QLabel(self.centralwidget)
        self.bg_2.setGeometry(QtCore.QRect(0, 0, 791, 571))
        self.bg_2.setStyleSheet("background-color: rgb(6, 157, 145);")
        self.bg_2.setText("")
        self.bg_2.setPixmap(QtGui.QPixmap("../G.U.I Material/VoiceReg/Ntuks.gif"))
        self.bg_2.setScaledContents(True)
        self.bg_2.setObjectName("bg_2")
        Lola.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Lola)
        self.statusbar.setObjectName("statusbar")
        Lola.setStatusBar(self.statusbar)

        self.retranslateUi(Lola)
        QtCore.QMetaObject.connectSlotsByName(Lola)

    def retranslateUi(self, Lola):
        _translate = QtCore.QCoreApplication.translate
        Lola.setWindowTitle(_translate("Lola", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Lola = QtWidgets.QMainWindow()
    ui = Ui_Lola()
    ui.setupUi(Lola)
    Lola.show()
    sys.exit(app.exec_())
